[profile.default]
solc_version   = "0.8.30"
optimizer      = true
optimizer_runs = 10000
via_ir         = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./script/json" },
    { access = "read", path = "./json" }
]

[profile.default.optimizer_details]
yul = true
yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]scLMcCTUtTOntnfDIul]jmul[jul] VcTOcul jmul" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Arbitrum One RPC URL (can be overridden with ARBITRUM_ONE_RPC_URL environment variable)
[rpc_endpoints]
arbitrum_one = "${ARBITRUM_ONE_RPC_URL:-https://arb1.arbitrum.io/rpc}"
buildbear = "https://rpc.buildbear.io/payable-mystique-f89040ff"

[profile.ci]
solc_version   = "0.8.30"
optimizer      = true
optimizer_runs = 10000
via_ir         = true

[profile.ci.optimizer_details]
yul = true
yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]scLMcCTUtTOntnfDIul]jmul[jul] VcTOcul jmul" }
